### ISSUE TITLE
misplaced " ?

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-sshd-host-keys#2]
" in here don't look good
https://github.com/CSC-IT-Center-for-Science/ansible-role-sshd-host-keys/blob/master/tasks/ssh_host_keys.yml#L6

**Comment by martbhell** [comment]
Ah.  You prefer it around the path only? Maybe it even works without it completely

**Comment by A1ve5** [comment]
If it works it's not a problem, it just looked like a typo. Closing it.
